apiVersion: skaffold/v2beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: s9ke/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*"]
        # manual:
        #   - src: '**/*.js'
        #     dest: .
        #   - src: '**/*.css'
        #     dest: .
        #   - src: '**/*.html'
        #     dest: .
    - image: s9ke/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*"]
    - image: s9ke/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*"]
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/database-persistent-volume-claim.yaml
      - k8s/ingress-service.yaml
      - k8s/postgres-cluster-ip-service.yaml
      - k8s/postgres-deployment.yaml
      - k8s/redis-cluster-ip-service.yaml
      - k8s/redis-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
